name: Printify Analytics Collection

on:
  # Run every day at 11:00 AM UTC (1:00 PM CET) - 1 hour after Traffic Analytics
  schedule:
    - cron: '0 11 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      date:
        description: 'Specific date to collect (YYYY-MM-DD, leave empty for yesterday)'
        required: false
        type: string

jobs:
  collect-printify-analytics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Printify analytics collection
      env:
        # Notion credentials
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        
        # Printify credentials
        PRINTIFY_API_TOKEN: ${{ secrets.PRINTIFY_API_TOKEN }}
        PRINTIFY_SHOP_ID: ${{ secrets.PRINTIFY_SHOP_ID }}
        
        # Database ID
        PRINTIFY_ANALYTICS_DB_ID: ${{ secrets.PRINTIFY_ANALYTICS_DB_ID }}
      run: |
        if [ -n "${{ inputs.date }}" ]; then
          echo "Running for specific date: ${{ inputs.date }}"
          python printify_analytics_scheduler.py "${{ inputs.date }}"
        else
          echo "Running for yesterday (default)"
          python printify_analytics_scheduler.py
        fi
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: printify-analytics-logs
        path: |
          *.log
          *.txt
        retention-days: 7