name: Traffic Analytics Collection

on:
  # Run every day at 10:30 AM UTC (12:30 PM CET) - 30 minutes after Financial Analytics
  schedule:
    - cron: '30 10 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      date:
        description: 'Specific date to collect (YYYY-MM-DD, leave empty for yesterday)'
        required: false
        type: string

jobs:
  collect-traffic-analytics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run traffic analytics collection
      env:
        # Notion credentials
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        
        # Shopify credentials
        SHOPIFY_SHOP_URL: ${{ secrets.SHOPIFY_SHOP_URL }}
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
      run: |
        if [ -n "${{ inputs.date }}" ]; then
          echo "Running for specific date: ${{ inputs.date }}"
          python traffic_analytics_scheduler.py "${{ inputs.date }}"
        else
          echo "Running for yesterday (default)"
          python traffic_analytics_scheduler.py
        fi
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: traffic-analytics-logs
        path: |
          *.log
          *.txt
        retention-days: 7